In [34]:
import sqlite3
import pandas as pd

# Load the first dataset
df1 = pd.read_csv(r"C:\Users\Kriwe\OneDrive\Documents\CodeKY Projects\CodeKY DA\Capstone\Datasets\kindle_data-v2.csv")

# Display the first few rows to understand its structure
df1.head()

,asin,title,author,soldBy,imgUrl,productURL,stars,reviews,price,isKindleUnlimited,category_id,isBestSeller,isEditorsPick,isGoodReadsChoice,publishedDate,category_name
0,B00TZE87S4,Adult Children of Emotionally Immature Parents...,Lindsay C. Gibson,Amazon.com Services LLC,https://m.media-amazon.com/images/I/713KZTsaYp...,https://www.amazon.com/dp/B00TZE87S4,4.8,0,9.99,False,6,True,False,False,2015-06-01,Parenting & Relationships
1,B08WCKY8MB,"From Strength to Strength: Finding Success, Ha...",Arthur C. Brooks,Penguin Group (USA) LLC,https://m.media-amazon.com/images/I/A1LZcJFs9E...,https://www.amazon.com/dp/B08WCKY8MB,4.4,0,16.99,False,6,False,False,False,2022-02-15,Parenting & Relationships
2,B09KPS84CJ,Good Inside: A Guide to Becoming the Parent Yo...,Becky Kennedy,HarperCollins Publishers,https://m.media-amazon.com/images/I/71RIWM0sv6...,https://www.amazon.com/dp/B09KPS84CJ,4.8,0,16.99,False,6,False,True,False,2022-09-13,Parenting & Relationships
3,B07S7QPG6J,Everything I Know About Love: A Memoir,Dolly Alderton,HarperCollins Publishers,https://m.media-amazon.com/images/I/71QdQpTiKZ...,https://www.amazon.com/dp/B07S7QPG6J,4.2,0,9.95,True,6,False,True,False,2020-02-25,Parenting & Relationships
4,B00N6PEQV0,The Seven Principles for Making Marriage Work:...,John Gottman,Random House LLC,https://m.media-amazon.com/images/I/813o4WOs+w...,https://www.amazon.com/dp/B00N6PEQV0,4.7,0,13.99,False,6,False,False,False,2015-05-05,Parenting & Relationships

In [35]:
# Load the second dataset
df2 = pd.read_csv(r"C:\Users\Kriwe\OneDrive\Documents\CodeKY Projects\CodeKY DA\Capstone\Datasets\book1-100k.csv")

# Display the first few rows to understand its structure
df2.head()

,Id,Name,RatingDist1,pagesNumber,RatingDist4,RatingDistTotal,PublishMonth,PublishDay,Publisher,CountsOfReview,PublishYear,Language,Authors,Rating,RatingDist2,RatingDist5,ISBN,RatingDist3
0,1,Harry Potter and the Half-Blood Prince (Harry ...,1:9896,652,4:556485,total:2298124,16,9,Scholastic Inc.,28062,2006,eng,J.K. Rowling,4.57,2:25317,5:1546466,NaN,3:159960
1,2,Harry Potter and the Order of the Phoenix (Har...,1:12455,870,4:604283,total:2358637,1,9,Scholastic Inc.,29770,2004,eng,J.K. Rowling,4.50,2:37005,5:1493113,0439358078,3:211781
2,3,Harry Potter and the Sorcerer's Stone (Harry P...,1:108202,309,4:1513191,total:6587388,1,11,Scholastic Inc,75911,2003,eng,J.K. Rowling,4.47,2:130310,5:4268227,NaN,3:567458
3,4,Harry Potter and the Chamber of Secrets (Harry...,1:11896,352,4:706082,total:2560657,1,11,Scholastic,244,2003,eng,J.K. Rowling,4.42,2:49353,5:1504505,0439554896,3:288821
4,5,Harry Potter and the Prisoner of Azkaban (Harr...,1:10128,435,4:630534,total:2610317,1,5,Scholastic Inc.,37093,2004,eng,J.K. Rowling,4.57,2:24849,5:1749958,043965548X,3:194848

In [37]:
conn = sqlite3.connect('books_db.sqlite')
df1.to_sql('amazon_books', conn, index=False, if_exists='replace') 
df2.to_sql('goodreads_books', conn, index=False, if_exists='replace')

58292

In [ ]:
print(df1.columns)
print(df2.columns)

In [ ]:
# Drop columns that aren't needed
df1.drop(columns=['imgUrl', 'productURL'], inplace=True)
df2.drop(columns=['RatingDist1', 'ISBN'], inplace=True)

In [ ]:
# print(df1.columns)

In [ ]:
# Add a 'source' column to distinguish the datasets
df1['source'] = 'Amazon'
df2['source'] = 'GoodReads'

In [ ]:
print(df1.head())
print(df2.head())

In [ ]:
# Convert 'publishedDate' to a datetime format, handling errors
df1['publishedDate'] = pd.to_datetime(df1['publishedDate'], errors='coerce')

# Extracting the year from 'publishedDate' and storing it in 'PublishYear'
df1['PublishYear'] = df1['publishedDate'].dt.year

# Display the first few rows to verify
print(df1[['publishedDate', 'PublishYear']].head())

In [ ]:
print(df1.isnull().sum())
print(df2.isnull().sum())

In [ ]:
df1['title'].head(15) 
df2['Name'].head(15)

In [ ]:
import re

# Clean up df1's titles by removing anything in parentheses
df1['cleaned_title'] = df1['title'].apply(lambda x: re.sub(r'\(.*\)', '', x).strip())

# Clean up df2's titles removing anything in parentheses
df2['cleaned_name'] = df2['Name'].apply(lambda x: re.sub(r'\(.*\)', '', x).strip())

# Check the first 15 cleaned titles for both datasets
print(df1['cleaned_title'].head(15))
print(df2['cleaned_name'].head(15))

In [ ]:
merged_df = pd.merge(df1, df2, left_on='cleaned_title', right_on='cleaned_name', how='inner')
print(merged_df.head())

In [ ]:
# Check for missing data
print(merged_df.isnull().sum())

# Check for duplicates
duplicates = merged_df.duplicated()
print(f'Duplicates: {duplicates.sum()}')

In [ ]:
# Filtering the dataset to only include books that are part of the Kindle Unlimited program
kindle_unlimited_books = merged_df[merged_df['isKindleUnlimited'] == True]

# Filter by a specific genre or price range
high_priced_books = merged_df[merged_df['price'] > 20]

In [ ]:
print(merged_df[['title', 'author']].head(10))

In [ ]:
# Check the shape (number of rows, number of columns)
print(merged_df.shape)

In [ ]:
# Get summary statistics for the numerical columns
print(merged_df.describe())

query = '''
SELECT * 
FROM amazon_books
LEFT JOIN goodreads_books 
ON amazon_books.title = goodreads_books.Name
'''
merged_df = pd.read_sql(query, conn)
print(merged_df.head())