In [2]:
import pandas as pd

# Load the first dataset
df1 = pd.read_csv(r"C:\Users\Kriwe\OneDrive\Documents\CodeKY Projects\CodeKY DA\Capstone\Datasets\kindle_data-v2.csv")

# Display the first few rows to understand its structure
df1.head()

,asin,title,author,soldBy,imgUrl,productURL,stars,reviews,price,isKindleUnlimited,category_id,isBestSeller,isEditorsPick,isGoodReadsChoice,publishedDate,category_name
0,B00TZE87S4,Adult Children of Emotionally Immature Parents...,Lindsay C. Gibson,Amazon.com Services LLC,https://m.media-amazon.com/images/I/713KZTsaYp...,https://www.amazon.com/dp/B00TZE87S4,4.8,0,9.99,False,6,True,False,False,2015-06-01,Parenting & Relationships
1,B08WCKY8MB,"From Strength to Strength: Finding Success, Ha...",Arthur C. Brooks,Penguin Group (USA) LLC,https://m.media-amazon.com/images/I/A1LZcJFs9E...,https://www.amazon.com/dp/B08WCKY8MB,4.4,0,16.99,False,6,False,False,False,2022-02-15,Parenting & Relationships
2,B09KPS84CJ,Good Inside: A Guide to Becoming the Parent Yo...,Becky Kennedy,HarperCollins Publishers,https://m.media-amazon.com/images/I/71RIWM0sv6...,https://www.amazon.com/dp/B09KPS84CJ,4.8,0,16.99,False,6,False,True,False,2022-09-13,Parenting & Relationships
3,B07S7QPG6J,Everything I Know About Love: A Memoir,Dolly Alderton,HarperCollins Publishers,https://m.media-amazon.com/images/I/71QdQpTiKZ...,https://www.amazon.com/dp/B07S7QPG6J,4.2,0,9.95,True,6,False,True,False,2020-02-25,Parenting & Relationships
4,B00N6PEQV0,The Seven Principles for Making Marriage Work:...,John Gottman,Random House LLC,https://m.media-amazon.com/images/I/813o4WOs+w...,https://www.amazon.com/dp/B00N6PEQV0,4.7,0,13.99,False,6,False,False,False,2015-05-05,Parenting & Relationships

In [3]:
# Load the second dataset
df2 = pd.read_csv(r"C:\Users\Kriwe\OneDrive\Documents\CodeKY Projects\CodeKY DA\Capstone\Datasets\book1-100k.csv")

# Display the first few rows to understand its structure
df2.head()

,Id,Name,RatingDist1,pagesNumber,RatingDist4,RatingDistTotal,PublishMonth,PublishDay,Publisher,CountsOfReview,PublishYear,Language,Authors,Rating,RatingDist2,RatingDist5,ISBN,RatingDist3
0,1,Harry Potter and the Half-Blood Prince (Harry ...,1:9896,652,4:556485,total:2298124,16,9,Scholastic Inc.,28062,2006,eng,J.K. Rowling,4.57,2:25317,5:1546466,NaN,3:159960
1,2,Harry Potter and the Order of the Phoenix (Har...,1:12455,870,4:604283,total:2358637,1,9,Scholastic Inc.,29770,2004,eng,J.K. Rowling,4.50,2:37005,5:1493113,0439358078,3:211781
2,3,Harry Potter and the Sorcerer's Stone (Harry P...,1:108202,309,4:1513191,total:6587388,1,11,Scholastic Inc,75911,2003,eng,J.K. Rowling,4.47,2:130310,5:4268227,NaN,3:567458
3,4,Harry Potter and the Chamber of Secrets (Harry...,1:11896,352,4:706082,total:2560657,1,11,Scholastic,244,2003,eng,J.K. Rowling,4.42,2:49353,5:1504505,0439554896,3:288821
4,5,Harry Potter and the Prisoner of Azkaban (Harr...,1:10128,435,4:630534,total:2610317,1,5,Scholastic Inc.,37093,2004,eng,J.K. Rowling,4.57,2:24849,5:1749958,043965548X,3:194848

In [4]:
# Basic info about both datasets
df1.info()
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133102 entries, 0 to 133101
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   asin               133102 non-null  object
 1   title              133102 non-null  object
 2   author             132677 non-null  object
 3   soldBy             123869 non-null  object
 4   imgUrl             133102 non-null  object
 5   productURL         133102 non-null  object
 6   stars              133102 non-null  float64
 7   reviews            133102 non-null  int64
 8   price              133102 non-null  float64
 9   isKindleUnlimited  133102 non-null  bool
 10  category_id        133102 non-null  int64
 11  isBestSeller       133102 non-null  bool
 12  isEditorsPick      133102 non-null  bool
 13  isGoodReadsChoice  133102 non-null  bool
 14  publishedDate      84086 non-null   object
 15  category_name      133102 non-null  object
dtypes: bool(4), float64(2), int64(2), object(8)
memory usage: 12.7+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58292 entries, 0 to 58291
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Id               58292 non-null  int64
 1   Name             58292 non-null  object
 2   RatingDist1      58292 non-null  object
 3   pagesNumber      58292 non-null  int64
 4   RatingDist4      58292 non-null  object
 5   RatingDistTotal  58292 non-null  object
 6   PublishMonth     58292 non-null  int64
 7   PublishDay       58292 non-null  int64
 8   Publisher        57798 non-null  object
 9   CountsOfReview   58292 non-null  int64
 10  PublishYear      58292 non-null  int64
 11  Language         20294 non-null  object
 12  Authors          58292 non-null  object
 13  Rating           58292 non-null  float64
 14  RatingDist2      58292 non-null  object
 15  RatingDist5      58292 non-null  object
 16  ISBN             57746 non-null  object
 17  RatingDist3      58292 non-null  object
dtypes: float64(1), int64(6), object(11)
memory usage: 8.0+ MB